### ISSUE TITLE
Cannot reset robot position in stage_ros

### ISSUE THREAD

**Issue by heleidsn** [ethz-asl/rl-navigation#3]
Hi, I am very interested in this work and thank you very much for open source the code. I want to repeat the experiment. But I find two problems:

1. I cannot reset the robot position:
https://github.com/ethz-asl/rl-navigation/blob/a1831d85c5ec3f6c76c4d9ed243cfd4b04407168/scripts/train_cpo.py#L156
It doesn't work.

2. I cannot receive the stalled message:
https://github.com/ethz-asl/rl-navigation/blob/a1831d85c5ec3f6c76c4d9ed243cfd4b04407168/scripts/environments/base_environment.py#L155

I used the Stage-ros simulator branch with **add_pose_sub** enabled as mentioned in Readme. 
I guess it is because of this [stage_ros branch](https://github.com/ros-simulation/stage_ros/tree/add_pose_sub) is not up to date. 

Did you do some modification on the stage_ros code? Where can I get the lasted stage_ros code which can set position? 

Looking for your reply! Thank you.

**Comment by heleidsn** [comment]
Problem fixed according to 
https://github.com/ros-simulation/stage_ros/pull/39
and 
https://github.com/ros-simulation/stage_ros/pull/42

Issues closed...

**Comment by shaohua-lyu** [comment]
Hello, I ran the code but met a problem.
The problem is that the loaded robot model can't run within the map.
I guess it's caused by that the coordinate system's origin of /odom and /map is mismatching, however I can't solve it.
![image](https://user-images.githubusercontent.com/48192000/92107591-a7cbd280-ee18-11ea-8d49-3b2d34b9eb61.png)

Can you help me? Looking forward to your reply. Thanks.
