### ISSUE TITLE
pre-training for the Imitation learning

### ISSUE THREAD

**Issue by lukewenMX** [ethz-asl/rl-navigation#5]
Hi, all. I am a Ph.D. student from NTU, Singapore and also work in the mapless navigation research direction. I must admit this is an amazing project, however, I am struggling with a problem. Are you training both Actor and Critic neural networks in the Imitation learning process? Look forward to your soon response. Thanks.

**Comment by Weeeesen** [comment]
@lukewenMX hi, I am an undergraduate in NUS, doing a project based on this paper as well and having some troubles including loading the pre-trained weights. If you don't mind, are there any way I could reach out to you for further discussions?

**Comment by pfmark** [comment]
The pre-training weights are only used to initialize the actor. I admit, this could be stated more clearly in the paper. Initializing the critic with the same weights would not make sense. The critic is trained from scratch in every training run.

**Comment by shaohua-lyu** [comment]
@lukewenMX @kermeed 
I ran the code but met a problem.
The problem is that the loaded robot model can't run within the map.
I guess it's caused by that the coordinate system's origin of /odom and /map is mismatching, however I can't solve it.
![rviz](https://user-images.githubusercontent.com/48192000/89372839-c8214800-d719-11ea-8289-888a676d513d.png)

Did you met the problem? Looking forward to your reply. Thanks.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by sumingzs11** [comment]
@minded-hua
Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by lukewenMX** [comment]
> @lukewenMX hi, I am an undergraduate in NUS, doing a project based on this paper as well and having some troubles including loading the pre-trained weights. If you don't mind, are there any way I could reach out to you for further discussions?

**Comment by minded-hua** [comment]
Hello, do you have a WeChat ID?&nbsp; We can talk with WeChat.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sumingzs11"<notifications@github.com&gt;; 
发送时间: 2020年9月2日(星期三) 中午11:05
收件人: "ethz-asl/rl-navigation"<rl-navigation@noreply.github.com&gt;; 
抄送: "奋斗"<1220073420@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ethz-asl/rl-navigation] pre-training for the Imitation learning (#5)





 
@minded-hua
 Hello,  I want to ask about the operation of the experiment. Whether I initialize or retrain, I never succeed once, and the robot always fails to reach the target point. I think it's probably a problem with my 2D simulator, stageros. I used the stageros simulator that came with ROS kinetic, but its clock was so slow that the training time was too long. So, I modified the time parameters, but I also found a problem, that is, the simulator can't send a stall signal, I don't know if it's because of this that my robot can't reach the target.

**Comment by shaohua-lyu** [comment]
@sumingzs11 Do you have a WeChat ID? We can talk with WeChat.

**Comment by sumingzs11** [comment]
Sorry, I was just having lunch. If you are willing to communicate on WeChat, that is really great. My wechat id is&nbsp;
ibelieveyouonly




---Original---

**Comment by sumingzs11** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ethz-asl/rl-navigation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 中午12:12
收件人:&nbsp;"ethz-asl/rl-navigation"<rl-navigation@noreply.github.com&gt;;
抄送:&nbsp;"苏铭"<847366070@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ethz-asl/rl-navigation] pre-training for the Imitation learning (#5)





 
@sumingzs11 Do you have a WeChat ID? We can talk with WeChat.
